/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author jhudy
 */
public class JFInfoPedido extends javax.swing.JFrame {

    /**
     * Creates new form JFInfoPedido
     */
    public JFInfoPedido() {
        initComponents();
    }

    public ButtonGroup getBtnGDistribuidor() {
        return btnGDistribuidor;
    }

    public void setBtnGDistribuidor(ButtonGroup btnGDistribuidor) {
        this.btnGDistribuidor = btnGDistribuidor;
    }

    public JButton getBtnVerificarDatos() {
        return btnVerificarDatos;
    }

    public void setBtnVerificarDatos(JButton btnVerificarDatos) {
        this.btnVerificarDatos = btnVerificarDatos;
    }

    public JComboBox<String> getCbxTipoMedicamento() {
        return cbxTipoMedicamento;
    }

    public void setCbxTipoMedicamento(JComboBox<String> cbxTipoMedicamento) {
        this.cbxTipoMedicamento = cbxTipoMedicamento;
    }

    public JCheckBox getChbxSucPrincipal() {
        return chbxSucPrincipal;
    }

    public void setChbxSucPrincipal(JCheckBox chbxSucPrincipal) {
        this.chbxSucPrincipal = chbxSucPrincipal;
    }

    public JCheckBox getChbxSucSecundaria() {
        return chbxSucSecundaria;
    }

    public void setChbxSucSecundaria(JCheckBox chbxSucSecundaria) {
        this.chbxSucSecundaria = chbxSucSecundaria;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JRadioButton getRbtnCemefar() {
        return rbtnCemefar;
    }

    public void setRbtnCemefar(JRadioButton rbtnCemefar) {
        this.rbtnCemefar = rbtnCemefar;
    }

    public JRadioButton getRbtnDisCofarma() {
        return rbtnDisCofarma;
    }

    public void setRbtnDisCofarma(JRadioButton rbtnDisCofarma) {
        this.rbtnDisCofarma = rbtnDisCofarma;
    }

    public JRadioButton getRbtnEmpsephar() {
        return rbtnEmpsephar;
    }

    public void setRbtnEmpsephar(JRadioButton rbtnEmpsephar) {
        this.rbtnEmpsephar = rbtnEmpsephar;
    }

    public JTextField getTxtCantidadProducto() {
        return txtCantidadProducto;
    }

    public void setTxtCantidadProducto(JTextField txtCantidadProducto) {
        this.txtCantidadProducto = txtCantidadProducto;
    }

    public JTextField getTxtnombreMedicamento() {
        return txtnombreMedicamento;
    }

    public void setTxtnombreMedicamento(JTextField txtnombreMedicamento) {
        this.txtnombreMedicamento = txtnombreMedicamento;
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGDistribuidor = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtnombreMedicamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbtnDisCofarma = new javax.swing.JRadioButton();
        rbtnEmpsephar = new javax.swing.JRadioButton();
        rbtnCemefar = new javax.swing.JRadioButton();
        chbxSucPrincipal = new javax.swing.JCheckBox();
        chbxSucSecundaria = new javax.swing.JCheckBox();
        cbxTipoMedicamento = new javax.swing.JComboBox<>();
        btnVerificarDatos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(22, 53, 77));

        txtnombreMedicamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtnombreMedicamento.setBorder(null);
        txtnombreMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreMedicamentoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre del medicamento:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo de medicamento:");

        txtCantidadProducto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCantidadProducto.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad de producto:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Distribuidor farmaceútico:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sucursal de la farmacia:");

        rbtnDisCofarma.setBackground(new java.awt.Color(22, 53, 77));
        btnGDistribuidor.add(rbtnDisCofarma);
        rbtnDisCofarma.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbtnDisCofarma.setForeground(new java.awt.Color(255, 255, 255));
        rbtnDisCofarma.setText("COFARMA");
        rbtnDisCofarma.setBorder(null);

        rbtnEmpsephar.setBackground(new java.awt.Color(22, 53, 77));
        btnGDistribuidor.add(rbtnEmpsephar);
        rbtnEmpsephar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbtnEmpsephar.setForeground(new java.awt.Color(255, 255, 255));
        rbtnEmpsephar.setText("EMPSEPHAR");
        rbtnEmpsephar.setBorder(null);

        rbtnCemefar.setBackground(new java.awt.Color(22, 53, 77));
        btnGDistribuidor.add(rbtnCemefar);
        rbtnCemefar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbtnCemefar.setForeground(new java.awt.Color(255, 255, 255));
        rbtnCemefar.setText("CEMEFAR");
        rbtnCemefar.setBorder(null);

        chbxSucPrincipal.setBackground(new java.awt.Color(22, 53, 77));
        chbxSucPrincipal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chbxSucPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        chbxSucPrincipal.setText("PRINCIPAL");
        chbxSucPrincipal.setBorder(null);

        chbxSucSecundaria.setBackground(new java.awt.Color(22, 53, 77));
        chbxSucSecundaria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chbxSucSecundaria.setForeground(new java.awt.Color(255, 255, 255));
        chbxSucSecundaria.setText("SECUNDARIA");
        chbxSucSecundaria.setBorder(null);

        cbxTipoMedicamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbxTipoMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Seleccione un tipo de medicamento", " Analgésico", " Analéptico", " Anestésico", " Antiácido", " Antidepresivo", " Antibióticos" }));
        cbxTipoMedicamento.setBorder(null);

        btnVerificarDatos.setBackground(new java.awt.Color(107, 153, 195));
        btnVerificarDatos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVerificarDatos.setText("OK");
        btnVerificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarDatosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PEDIDOS FARMACIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombreMedicamento)
                            .addComponent(cbxTipoMedicamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidadProducto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnDisCofarma)
                                    .addComponent(chbxSucPrincipal))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chbxSucSecundaria)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtnEmpsephar)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtnCemefar)))
                                .addGap(0, 12, Short.MAX_VALUE)))))
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(btnVerificarDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(txtnombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbxTipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbtnDisCofarma)
                    .addComponent(rbtnEmpsephar)
                    .addComponent(rbtnCemefar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(chbxSucPrincipal)
                    .addComponent(chbxSucSecundaria))
                .addGap(38, 38, 38)
                .addComponent(btnVerificarDatos)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarDatosActionPerformed
        // TODO add your handling code here:
        JFPedido p = new JFPedido();
        p.setVisible(true);
    }//GEN-LAST:event_btnVerificarDatosActionPerformed

    private void txtnombreMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreMedicamentoActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInfoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInfoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInfoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInfoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFInfoPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGDistribuidor;
    private javax.swing.JButton btnVerificarDatos;
    private javax.swing.JComboBox<String> cbxTipoMedicamento;
    private javax.swing.JCheckBox chbxSucPrincipal;
    private javax.swing.JCheckBox chbxSucSecundaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtnCemefar;
    private javax.swing.JRadioButton rbtnDisCofarma;
    private javax.swing.JRadioButton rbtnEmpsephar;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtnombreMedicamento;
    // End of variables declaration//GEN-END:variables
}
